const $=id=>document.getElementById(id);
const segOrder=['large','mid','small'];
const f=(v,d=1)=>v==null||Number.isNaN(Number(v))?'--':Number(v).toFixed(d);
const pct=(v,s=true)=>v==null?'--':`${s&&Number(v)>0?'+':''}${f(v)}%`;
const pp=v=>v==null?'--':`${Number(v)>0?'+':''}${f(v)} pp`;
const x=v=>v==null?'--':`${f(v,2)}x`;
const cr=v=>v==null?'--':`${Number(v)>=0?'+':''}₹${Math.abs(Number(v)).toLocaleString('en-IN',{maximumFractionDigits:0})} Cr`;
function tonePct(v){if(v==null)return'tone-neutral';if(v<=25)return'tone-good';if(v>=75)return'tone-bad';if(v>=60)return'tone-warn';return'tone-neutral'}
function condTone(s){s=(s||'').toLowerCase();if(s.includes('below'))return'cheap';if(s.includes('above'))return'expensive';return'fair'}
function stanceClass(s){s=(s||'').toLowerCase();if(s.includes('positive')||s.includes('constructive'))return'pos';if(s.includes('cautious'))return'caut';return'neutral'}
function card(k,s){return `<article class="cap-card ${k}"><div class="cap-top"><div><div class="cap-name">${s.label}</div><div class="index-name">${s.index}</div></div><div class="condition ${condTone(s.valuation_condition)}">${s.valuation_condition||'--'}</div></div><div class="kpis"><div><span>P/E</span><strong>${f(s.pe,2)}x</strong></div><div><span>P/E percentile</span><strong class="${tonePct(s.pe_5y_percentile)}">${f(s.pe_5y_percentile,0)}%</strong></div><div><span>P/B percentile</span><strong class="${tonePct(s.pb_5y_percentile)}">${f(s.pb_5y_percentile,0)}%</strong></div><div><span>ROE proxy</span><strong>${pct(s.roe_proxy_pct,false)}</strong></div></div></article>`}
function metricRow(label,a,b){return `<div class="metric-row"><div>${label}</div><div>${a}</div><div>${b}</div></div>`}
function render(data){
  $('asOf').textContent=data.as_of||'--'; $('version').textContent=data.methodology_version||'--';
  const health=Object.values(data.source_health||{}); const live=health.filter(x=>x.status==='live').length; const bad=health.filter(x=>['cached','unavailable'].includes(x.status)).length;
  const status=bad===0?'live':live>0?'partial':'cached'; $('statusDot').className=`dot ${status}`; $('statusText').textContent=status==='live'?'Sources healthy':status==='partial'?'Some sources unavailable':'Using cached/seed data';
  $('cards').innerHTML=segOrder.map(k=>card(k,data.segments[k])).join('');
  const g=data.gsec_10y?.yield_pct;
  $('coreTable').innerHTML=segOrder.map(k=>{const s=data.segments[k];return `<tr><td><b>${s.label}</b><br><small>${s.index}</small></td><td>${f(s.pe,2)}x</td><td class="${tonePct(s.pe_5y_percentile)}">${f(s.pe_5y_percentile,0)}%</td><td>${f(s.pb,2)}x</td><td class="${tonePct(s.pb_5y_percentile)}">${f(s.pb_5y_percentile,0)}%</td><td>${k==='large'?'—':x(s.relative_pe_vs_large)}</td><td class="${tonePct(s.relative_premium_5y_percentile)}">${k==='large'?'—':f(s.relative_premium_5y_percentile,0)+'%'}</td><td>${pct(s.earnings_yield_pct,false)}</td><td>${g==null?'--':pct(g,false)}</td><td>${pp(s.equity_bond_spread_pp)}</td><td>${pct(s.earnings_growth_1y_pct)}</td><td>${pct(s.earnings_cagr_3y_pct)}</td><td>${pct(s.roe_proxy_pct,false)}</td><td>${pct(s.dividend_yield,false)}</td></tr>`}).join('');
  $('trendGrid').innerHTML=segOrder.map(k=>{const s=data.segments[k],t=s.trend||{};return metricRow(s.label,`<strong>${pct(t.vs_50dma_pct)}</strong><small>vs 50DMA</small>`,`<strong>${pct(t.vs_200dma_pct)}</strong><small>vs 200DMA</small>`)}).join('');
  $('breadthGrid').innerHTML=segOrder.map(k=>{const s=data.segments[k],b=s.breadth||{},proxy=b.proxy_index||'proxy';return metricRow(s.label,`<strong>${pct(b.above_50dma_pct,false)}</strong><small>>50DMA · ${proxy}</small>`,`<strong>${pct(b.above_200dma_pct,false)}</strong><small>>200DMA · ${proxy}</small>`)}).join('');
  $('referenceGrid').innerHTML=Object.entries(data.references||{}).map(([k,r])=>metricRow(k==='nifty50'?'Nifty 50':'Nifty 500',`<strong>${pct(r.vs_50dma_pct)}</strong><small>vs 50DMA · breadth ${pct(r.breadth_50dma_pct,false)}</small>`,`<strong>${pct(r.vs_200dma_pct)}</strong><small>vs 200DMA · breadth ${pct(r.breadth_200dma_pct,false)}</small>`)).join('');
  const fd=data.fii_dii||{}; $('flowGrid').innerHTML=`<div class="flow-card"><h3>FII / FPI</h3><div class="big ${Number(fd.latest_fii)>=0?'tone-good':'tone-bad'}">${cr(fd.latest_fii)}</div><div class="sub"><div><span>5 trading days</span><b>${cr(fd.fii_5d)}</b></div><div><span>20 trading days</span><b>${cr(fd.fii_20d)}</b></div></div></div><div class="flow-card"><h3>DII</h3><div class="big ${Number(fd.latest_dii)>=0?'tone-good':'tone-bad'}">${cr(fd.latest_dii)}</div><div class="sub"><div><span>5 trading days</span><b>${cr(fd.dii_5d)}</b></div><div><span>20 trading days</span><b>${cr(fd.dii_20d)}</b></div></div></div>`;
  $('consensusTable').innerHTML=(data.external_consensus||[]).map(c=>{const L=c.large||{},M=c.mid||{},S=c.small||{};const ev=L.evidence||M.evidence||S.evidence||c.note||'';return `<tr><td><b>${c.name}</b></td><td><span class="stance ${stanceClass(L.stance)}">${L.stance||'No explicit view'}</span></td><td><span class="stance ${stanceClass(M.stance)}">${M.stance||'No explicit view'}</span></td><td><span class="stance ${stanceClass(S.stance)}">${S.stance||'No explicit view'}</span></td><td>${ev}</td><td>${c.reliability||'--'}</td></tr>`}).join('');
  $('healthGrid').innerHTML=Object.entries(data.source_health||{}).map(([k,h])=>`<div class="health-card"><strong>${k.replaceAll('_',' ')}</strong><span class="health-pill ${h.status||''}">${h.status||'--'}</span></div>`).join('');
  $('disclaimer').textContent=data.disclaimer||'';
}
fetch('data/latest.json',{cache:'no-store'}).then(r=>r.json()).then(render).catch(e=>{$('statusText').textContent='Could not load data';console.error(e)});
